name: ez_ui
description: UI Toolkit for the App Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  backdrop: ^0.9.0
  badges: ^3.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  collection: ^1.17.0
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_typeahead: ^4.3.7
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.1
  image: ^4.0.17
  image_cropper: ^9.1.0
  image_picker: ^1.0.0
  path: ^1.8.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.1.0
  shimmer: ^3.0.0
  signature: ^5.4.0
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
