name: ez_firebase
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  firebase_auth: ^4.3.0
  firebase_core: 2.12.0
  firebase_core_platform_interface: ^4.5.2
  firebase_crashlytics: 3.3.0
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: 4.4.1+1
  google_sign_in: ^6.0.2
  import_sorter: ^4.6.0
  sign_in_with_apple: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
